
version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - '5433:5432'
    volumes:
      - community-feedback-postgres:/var/lib/postgresql/data

  community-feedback-backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - "5000:5000"
        
volumes:
  community-feedback-postgres: